logging:

  level:

    ROOT: ${log-framework:WARN}

    ru.tchallenge: ${log:INFO}

server:

  error.whitelabel.enabled: 'false'

  port: ${port:3000}

spring:

  mail:
    host: ${mail-host:localhost}
    port: ${mail-port:25}
    username: ${mail-username:}
    password: ${mail-password:}

  main.banner-mode: 'off'

  mvc.throw-exception-if-no-handler-found: 'true'

  resources.add-mappings: 'false'

tchallenge:

  security:

    certificate:

      payload:

        header: 'X-Security-Certificate'

    token:

      payload:

        header: 'X-Security-Token'

      predefined:

        employee:
          enabled: true
          login: 'ipetrov'
          payload: 'EMPLOYEE'

    voucher:
      expirationInMinutes: 15
